# Generated by Django 4.1.3 on 2022-12-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='category title')),
                ('slug', models.SlugField(unique=True, verbose_name='category slug')),
            ],
            options={
                'verbose_name': 'Instrument Category',
                'verbose_name_plural': 'Instrument Categories',
                'ordering': ('title',),
            },
        ),
    ]
