# Generated by Django 4.1.3 on 2022-12-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentcategory',
            options={'ordering': ('-title',), 'verbose_name': 'Instrument Category', 'verbose_name_plural': 'Instrument Categories'},
        ),
    ]
