# Generated by Django 4.1.3 on 2023-01-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('category',), 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
    ]
