# Generated by Django 4.1.3 on 2022-12-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_band_instrument_userbandinstrument_request_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ('title',), 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
    ]
