# Generated by Django 4.1.3 on 2022-12-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_instrument_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='is_full',
            field=models.BooleanField(default=False, null=True, verbose_name='is_full'),
        ),
        migrations.AlterField(
            model_name='band',
            name='is_visible',
            field=models.BooleanField(default=True, null=True, verbose_name='is_visible'),
        ),
    ]
