# Generated by Django 4.1.3 on 2022-12-03 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0008_remove_band_creator_remove_request_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='request',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='is_accepted'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='is_accepted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_invite', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_user', to='info.band', verbose_name='band')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_invite', to='info.instrument', verbose_name='instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invite', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
                'ordering': ('id',),
            },
        ),
    ]
