# Generated by Django 4.1.3 on 2022-12-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_remove_request_is_approved_request_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='poster',
            field=models.ImageField(default=None, upload_to='bands/posters/', verbose_name='poster'),
        ),
    ]
