# Generated by Django 4.1.3 on 2022-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_band_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='bands/posters/', verbose_name='poster'),
        ),
    ]
